### PR TITLE
🐛 Option :snaky should default to true

### LINKED ISSUE #617: snaky default bug
Dhe default value of `true` is not working properly in the current version (see comment below)

_Originally posted by @jeromepl in https://github.com/oauth-xx/oauth2/pull/612#pullrequestreview-1021698182_

### PR DESCRIPTION
**Pull request by pboling**
- Fixes #617

Also line coverage @ 100% and branch coverage at 97%

Signed-off-by: Peter Boling <peter.boling@gmail.com>

### CODE REVIEW

File: lib/oauth2/client.rb [hunk 1]
```diff
@@ -167,10 +167,9 @@ def get_token(params, access_token_opts = {}, extract_access_token = nil, &block
 
       request_opts = {
         raise_errors: options[:raise_errors],
-        parse: params.delete(:parse),
-        snaky: params.delete(:snaky),
+        parse: params.fetch(:parse, Response::DEFAULT_OPTIONS[:parse]),
```
Comment (chrisandreae) [inline lib/oauth2/client.rb:170]: This change introduces a bug: by no longer deleting the `parse` or `snaky` parameters from the `params` hash, it results in them getting sent to the oauth server as part of the request body.
